import Symptom from "./symptom.tsx"
import Illness from "./illness.tsx"
import Data from "./data.tsx"

export default function get_data(): Data{
        
    let first_symptoms = [
        new Symptom(1, "Бессонница", []),
        new Symptom(2, "Боли в глазах", []),
        new Symptom(3, "Боли в животе", []),
        new Symptom(4, "Боли в мыщцах, костях, суставах", []),
        new Symptom(5, "Боли в правом подреберье", []),
        new Symptom(6, "Головная боль", []),
        new Symptom(7, "Головокружение", []),
        new Symptom(8, "Жажда", []),
        new Symptom(9, "Запоры", []),
        new Symptom(10, "Кашель", []),
        new Symptom(11, "Кожа бледная", []),
        new Symptom(12, "Кожный зуд", []),
        new Symptom(13, "Лихорадка", []),
        new Symptom(14, "Лицо, шея, верхние отделы груди и спины гиперемированы", []),
        new Symptom(15, "Метеоризм", []),
        new Symptom(16, "Нарушение стула", []),
        new Symptom(17, "На сильно покрасневшей слизистой оболочке полости рта белесовато-желтый налет", []),
        new Symptom(18, "Недомогание", []),
        new Symptom(19, "Обильный пот", []),
        new Symptom(20, "Ознобы", []),
        new Symptom(21, "Отдышка", []),
        new Symptom(22, "Повышенная, утомляемость", []),
        new Symptom(23, "Повышенное слюноотделение", []),
        new Symptom(24, "Познабливание", []),
        new Symptom(25, "Понос", []),
        new Symptom(26, "Постоянные или схваткообразные боли в области желудка", []),
        new Symptom(27, "Потеря аппетита", []),
        new Symptom(28, "Рвота", []),
        new Symptom(29, "Слабость", []),
        new Symptom(30, "Снижение массы тела", []),
        new Symptom(31, "Снижение работоспособности", []),
        new Symptom(32, "Сосание и жевание болезнены", []),
        new Symptom(33, "Сухость во рту", []),
        new Symptom(34, "Температура", []),
        new Symptom(35, "Тошнота", []),
        new Symptom(36, "Увеличение лимфоузлов", []),
        new Symptom(37, "Ухудшение сна", []),
        new Symptom(38, "Частый стул", []),
        new Symptom(39, "Красные симметричные пятна на коже", []),
        new Symptom(40, "Утолщение нервных стволов", []),
        new Symptom(41, "Поражение ЦНС", []),
        new Symptom(42, "Пневмония", []),
        new Symptom(43, "Гепатолиенальный синдром", []),
    ]
    let second_symptoms: Symptom[] = [
        new Symptom(44, "Плохое самочувствие", [first_symptoms[21],  first_symptoms[5]]),
        new Symptom(45, "Болезненное состояние легких", [first_symptoms[9], first_symptoms[20]]),
        new Symptom(46, "Заболевание трахеи", [first_symptoms[20], first_symptoms[35]]),
        new Symptom(47, "Поражение кишечника", [first_symptoms[8],  first_symptoms[34],]),
        new Symptom(48, "Диарея", [first_symptoms[24],  first_symptoms[2]]),
        new Symptom(49, "Кислотность желудка", [first_symptoms[2],  first_symptoms[32]]),
        new Symptom(50, "Отеки кожи", [first_symptoms[11], first_symptoms[38],]),
        new Symptom(51, "Изменения в текстуре кожи", [first_symptoms[10], first_symptoms[39]]),
        new Symptom(52, "Боли в горле", [first_symptoms[9], first_symptoms[33]]),
        new Symptom(53, "Нарушение вкуса", [first_symptoms[32], first_symptoms[26],]),
        new Symptom(54, "Судороги", [first_symptoms[29], first_symptoms[42]]),
        new Symptom(55, "Ощущения покалывания или онемения в частях тела", [first_symptoms[24], first_symptoms[41],]),
        new Symptom(56, "Потеря чувствительности", [first_symptoms[33], first_symptoms[13]]),
        new Symptom(57, "Раздражительность", [first_symptoms[40], first_symptoms[36], ]),
        new Symptom(58, "Тревожность или депрессивность", [first_symptoms[0],  first_symptoms[26]]),
    ]
    let third_symptoms: Symptom[] = [
        new Symptom(59, "Общие зараженные состояния", [second_symptoms[0], first_symptoms[33]]),
        new Symptom(60, "Симптомы дыхательной системы", [second_symptoms[1], second_symptoms[2],]),
        new Symptom(61, "Симптомы пищеварительной системы", [second_symptoms[3], second_symptoms[5]]),
        new Symptom(62, "Симптомы кожи и слизистых оболочек", [second_symptoms[6]]),
        new Symptom(63, "Неврологические симптомы", [second_symptoms[12], first_symptoms[39]]),
        new Symptom(64, "Изменения психики и поведения", [second_symptoms[13], second_symptoms[14]]),
    ]
    
    let illnesses = [
        new Illness(1, "ботулизм", [
            third_symptoms[0],
            first_symptoms[6],
            first_symptoms[34],
        ], 
        //(await import(`./knowledge-as-rules-diagnoses/` + "ботулизм" + `.txt?raw`)).default),
        ""),
        new Illness(2, "бруцеллез", [
            second_symptoms[1],
            first_symptoms[19],
            first_symptoms[7],
        ], 
        //(await import(`./knowledge-as-rules-diagnoses/` + "бруцеллез" + `.txt?raw`)).default),
        ""),
        new Illness(3, "геморрагическая лихорадка с почечным синдромом", [
            third_symptoms[1],
            third_symptoms[0],
            first_symptoms[12],
        ], 
        //(await import(`./knowledge-as-rules-diagnoses/` + "геморрагическая лихорадка с почечным синдромом" + `.txt?raw`)).default),
        ""),
        new Illness(4, "гепатит", [
            third_symptoms[4],
            second_symptoms[0],
            first_symptoms[33],
        ], 
        //(await import(`./knowledge-as-rules-diagnoses/` + "гепатит" + `.txt?raw`)).default),
        ""),
        new Illness(5, "дисбактериоз кишечника", [
            third_symptoms[2],
            first_symptoms[26],
            second_symptoms[4],
        ], 
        //(await import(`./knowledge-as-rules-diagnoses/` + "дисбактериоз кишечника" + `.txt?raw`)).default),
        ""),
        new Illness(6, "дизентерия", [
            third_symptoms[2],
            second_symptoms[6],
            first_symptoms[34],
        ], 
        //(await import(`./knowledge-as-rules-diagnoses/` + "дизентерия" + `.txt?raw`)).default),
        ""),
        new Illness(7, "кандидоз", [
            first_symptoms[16],
            first_symptoms[31],
        ], 
        //(await import(`./knowledge-as-rules-diagnoses/` + "кандидоз" + `.txt?raw`)).default),
        ""),
        new Illness(8, "туберкулез", [
            third_symptoms[2],
            second_symptoms[0],
            first_symptoms[9],
        ], 
        //(await import(`./knowledge-as-rules-diagnoses/` + "туберкулез" + `.txt?raw`)).default),
        ""),
        new Illness(9, "чесотка", [
            third_symptoms[3],
            first_symptoms[0],
        ], 
        //(await import(`./knowledge-as-rules-diagnoses/` + "чесотка" + `.txt?raw`)).default),
        ""),
        new Illness(10, "лепра", [
            third_symptoms[3],
            second_symptoms[7],
            first_symptoms[38],
        ], 
        //(await import(`./knowledge-as-rules-diagnoses/` + "лепра" + `.txt?raw`)).default),
        ""),
        new Illness(11, "нокардиоз", [
            third_symptoms[4],
            first_symptoms[39],
        ], 
        //(await import(`./knowledge-as-rules-diagnoses/` + "нокардиоз" + `.txt?raw`)).default),
        ""),
        new Illness(12, "орнитоз", [
            third_symptoms[0],
            second_symptoms[1],
            first_symptoms[41],
        ], 
        //(await import(`./knowledge-as-rules-diagnoses/` + "орнитоз" + `.txt?raw`)).default),
        "")
    ]
    return new Data(illnesses, first_symptoms, second_symptoms, third_symptoms)
}
